server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ruta-autenticacion
              uri: lb://AUTENTICACION
              predicates:
                - Path=/autenticacion,/autenticacion/**

            - id: ruta-pagos
              uri: lb://PAGOS
              predicates:
                - Path=/pagos,/pagos/**
            - id: ruta-examenes
              uri: lb://EXAM-SERVICE
              predicates:
                - Path=/examenes,/examenes/**

            - id: ruta-recetas
              uri: lb://RECIPE-SERVICE
              predicates:
                - Path=/recetas,/recetas/**

            - id: ruta-reviews
              uri: lb://REVIEWS-SERVICE
              predicates:
                - Path=/reviews,/reviews/**
            - id: ruta-notificaciones
              uri: lb://NOTIFICACIONES
              predicates:
                - Path=/notificaciones,/notificaciones/**

            - id: ruta-servicios
              uri: lb://SERVICIOS
              predicates:
                - Path=/servicios,/servicios/**

            - id: ruta-mascotas
              uri: lb://FICHA
              predicates:
                - Path=/api/mascotas,/api/mascotas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG