server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ruta-autenticacion
          uri: lb://autenticacion
          predicates:
            - Path=/registro,/registro/**

        - id: ruta-pagos
          uri: lb://pagos
          predicates:
            - Path=/pagos,/pagos/**

        - id: ruta-examenes
          uri: lb://exam-service
          predicates:
            - Path=/examenes,/examenes/**

        - id: ruta-recetas
          uri: lb://recipe-service
          predicates:
            - Path=/recetas,/recetas/**

        - id: ruta-reviews
          uri: lb://reviews-service
          predicates:
            - Path=/reviews,/reviews/**

        - id: ruta-notificaciones
          uri: lb://notificaciones
          predicates:
            - Path=/notificaciones,/notificaciones/**

        - id: ruta-servicios
          uri: lb://servicios
          predicates:
            - Path=/servicios,/servicios/**

        - id: ruta-mascotas
          uri: lb://ficha
          predicates:
            - Path=/api/mascotas,/api/mascotas/**

        - id: ruta-reservas
          uri: lb://reservas
          predicates:
            - Path=/reservas,/reservas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG